variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: -ffdx -e cache/
    GIT_DEPTH: "3"
    GIT_CLONE_PATH: $CI_BUILDS_DIR
    ABS_REPO: "https://www.eduvax.net/dist"

stages:
    - test

.test_base:
    only:
        - branches
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release"
    script:
        - echo make -C sampleprj test $TASK_OPTVAR
        # disable SVN_CHECKOUTS that need internet access.
        - echo "SVN_CHECKOUTS=" >> sampleprj/cpplib/module.cfg
        - echo "ABS_REPO=$ABS_REPO" > sampleprj/local.cfg
        - make -C sampleprj test $TASK_OPTVAR
        - egrep -ri 'errors="[1-9]+' sampleprj/build/unit_test_results && exit 1 || echo "ok"
        - egrep -ri 'failures="[1-9]+' sampleprj/build/unit_test_results && exit 1 || echo "ok"

test_debian_11:
    extends: .test_base
    tags:
        - debian_11

test_suse_12:
    extends: .test_base
    tags:
        - suse_12
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release DISABLE_DYN_RUST=true"
        

test_suse_15sp5:
    extends: .test_base
    tags:
        - suse_15sp5
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release DISABLE_DYN_RUST=true"
