# ---------------------------------------------------------------------
# Java build rules
# ---------------------------------------------------------------------

# default compiler commands
PATH_SEP?=$(if $(ISWINDOWS),;,:)
JAVA?=java
JAR?=jar
JC?=javac
JDB?=jdb

# ---------------------------------------------------------------------
# Compilation flags by compilation modes
# ---------------------------------------------------------------------
ifeq ($(MODE),debug)
# debugging symbols
	JFLAGS+= -g
else
# no debbugging symbol
	JFLAGS+= -g:none
endif

# Main target definition
ifeq ($(APPNAME),$(MODNAME))
TARGET=$(DOMAIN).$(APPNAME)-$(VERSION).jar
else
TARGET=$(DOMAIN).$(APPNAME).$(MODNAME)-$(VERSION).jar
endif
TARGETDIR=$(TRDIR)/lib
TARGETFILE=$(TARGETDIR)/$(TARGET)
# Java default settings
JCLASSES:=$(patsubst src/%.java,$(OBJDIR)/%.class,$(filter %.java, $(SRCFILES)))
CLASSPATH:=$(subst !!,,$(subst !! ,:,$(patsubst %,$(NA_EXTLIBDIR)/%.jar!!,$(USEJAR)) $(patsubst $(TARGETDIR)/$(DOMAIN).$(APPNAME).$(APPNAME).%,$(TARGETDIR)/$(DOMAIN).$(APPNAME).%,$(patsubst %,$(TARGETDIR)/$(DOMAIN).$(APPNAME).%-$(VERSION).jar!!,$(USEJMOD)))))
ifeq ($(ISWINDOWS),true)
CLASSPATH:=$(shell cygpath -mp $(CLASSPATH))
endif
ifeq ($(ISWINDOWS),true)
JFLAGS+=-cp "${CLASSPATH}" -d `cygpath -m $(OBJDIR)`
JCFLAGS:=$(JFLAGS) -sourcepath "src;$(shell cygpath -m $(OBJDIR))"
else
JFLAGS+=-cp "${CLASSPATH}" -d $(OBJDIR)
JCFLAGS:=$(JFLAGS) -sourcepath "src:$(OBJDIR)"
endif
RESFILES=$(patsubst src/%,$(OBJDIR)/%,$(filter-out %.java src/test/%,$(SRCFILES)))

# ---------------------------------------------------------------------
# Default target : build target file
# ---------------------------------------------------------------------
all-impl:: $(TARGETFILE)

# ---------------------------------------------------------------------
# Main transformation rules
# ---------------------------------------------------------------------
# Java file compilation
$(OBJDIR)/%.class: src/%.java
	@$(ABS_PRINT_info) "Compiling $< ..."
	@mkdir -p $(OBJDIR)
	@echo `date --rfc-3339 s`'> $(JC) $(JCFLAGS) $<' >> $(TRDIR)/build.log
	@$(JC) $(JCFLAGS) $(if $(ISWINDOWS),`cygpath -m $<`,$<) || ( echo 'Failed: JFLAGS=$(JCFLAGS)' ; exit 1 )

# Resource file copy
$(OBJDIR)/%: src/%
	@$(ABS_PRINT_info) "Installing resource $< ..."
	@mkdir -p $(@D)
	@cp $< $@

# external dependancies and module dependancies.
$(JCLASSES): $(patsubst %,$(NA_EXTLIBDIR)/%.jar,$(USEJAR)) $(patsubst %,$(TARGETDIR)/$(DOMAIN).$(APPNAME).%-$(VERSION).jar,$(USEJMOD))

$(TARGETDIR)/$(MODNAME).Manifest: $(JCLASSES)
	@$(ABS_PRINT_info) "Creating manifest file..."
	@mkdir -p $(@D)
	@echo "Main-Class: $(MAINCLASS)" > $@
	@echo "Class-Path: $(patsubst %,%.jar,$(USEJAR)) ../res" >> $@
	@echo "Implementation-Version: $(VERSION)-$(REVISION)" >> $@
	@echo "Implementation-Vendor: $(COMPANY)" >> $@
	@echo "Copyright: $(COPYRIGHT)" >> $@
	@echo "Build-Date: "`date` >> $@
	@echo "Build-Host: "`hostname` >> $@
	@echo "Build-User: "`whoami` >> $@
	@echo "Build-Option: $(MODE) $(DEFINES)" >> $@
	@echo "Build-Id: $(BUILDNUM)" >> $@

# Jar archive
$(TARGETFILE): $(TARGETDIR)/$(MODNAME).Manifest $(RESFILES)
	@$(ABS_PRINT_info) "Building jar archive $@ ..."
	@mkdir -p $(TARGETDIR)
	@echo `date --rfc-3339 s`'> $(JAR) cf $@ -C $(OBJDIR) .' >> $(TRDIR)/build.log
ifeq ($(ISWINDOWS),true)
	$(JAR) cf `cygpath -m $@` -C `cygpath -m $(OBJDIR)` .
else
	$(JAR) cf $@ -C $(OBJDIR) .
endif
	@echo `date --rfc-3339 s`'$(JAR) umf $(TARGETDIR)/Manifest $@' >> $(TRDIR)/build.log
ifeq ($(ISWINDOWS),true)
	@$(JAR) umf `cygpath -m $(TARGETDIR)/$(MODNAME).Manifest` `cygpath -m $@`
else
	@$(JAR) umf $(TARGETDIR)/$(MODNAME).Manifest $@
endif

# ---------------------------------------------------------------------
#  dependences beetween modules
# ---------------------------------------------------------------------
# used module jar is generated by running make from the module's path
$(TARGETDIR)/$(DOMAIN).$(APPNAME).%-$(VERSION).jar: $(PRJROOT)/%/Makefile
	make -C $(<D)

# used module jar is generated by running make from the module's path
$(TARGETDIR)/$(DOMAIN).$(APPNAME).%-$(VERSION).jar: ../%/Makefile
	make -C $(<D)

# ---------------------------------------------------------------------
# Run & debug rules
# ---------------------------------------------------------------------
run:: all
ifeq ($(ISWINDOWS),true)
	$(JAVA) -cp "$(CLASSPATH);$(shell cygpath -m $(TARGETFILE))" $(MAINCLASS) $(RUNARGS)
else
	$(JAVA) -cp "$(CLASSPATH):$(TARGETFILE)" $(MAINCLASS) $(RUNARGS)
endif

debug:: all
	$(JDB) -classpath "$(CLASSPATH)$(PATH_SEP)$(TARGETFILE)" -sourcepath src $(MAINCLASS) $(RUNARGS)

ifneq ($(INCTESTS),)
  include $(ABSROOT)/core/module-junit.mk
endif
