# ---------------------------------------------------------------------
# Rust Cargo management
# ---------------------------------------------------------------------
ifeq ($(MODE),release)
CARGO_OPTS+=--release
endif

# not recommended option. The dynamic libraries in RUST is unstable
ifeq ($(CARGO_DYNAMIC),true)

RUSTFLAGS=-C prefer-dynamic
INCLUDE_MODS+=rust

endif

RUST_EDITION?=2021

# Cargo.toml to permit the use of dev tools to find sources (or to compile via Cargo tool).
CARGO_TOML=$(MODROOT)/Cargo.toml
CARGO_TOML_TEMPLATE=$(MODROOT)/Cargo_template.toml

# common obj dir to avoid recompilation of libraries
RUST_TARGET_DIR=$(PRJOBJDIR)/_rust_cargo/target
RUST_CARGO_EXECUTED=$(OBJDIR)/cargo.executed
RUST_EXTLIB_WITH_RSFILES=$(patsubst $(EXTLIBDIR)/%/src/lib.rs,%,$(foreach lib,$(USELIB_FOR_PATH),$(wildcard $(EXTLIBDIR)/$(lib)/src/*/src/lib.rs)))

ifeq ($(CARGO_DYNAMIC),true)
RUSTFLAGS+=$(foreach MOD,$(USEMOD),--extern $(APPNAME)_$(MOD)=$(TRDIR)/lib/lib$(APPNAME)_$(MOD).so)
else
RUST_DEPENDS_TEXT=$(subst $(SPACE) ,\n,$(foreach mod,$(USEMOD),$(APPNAME)_$(mod)={path=\"../$(mod)\"}) $(foreach extlib,$(RUST_EXTLIB_WITH_RSFILES),$(lastword $(subst /, ,$(extlib)))={path=\"$(EXTLIBDIR)/$(extlib)\"}))
endif

# RUST_BIN_DIR => directory of rust binaries
RUST_BIN_DIR?=
# RUST_BIN_DIR must be first in PATH to avoid using installed rust toolchain
# Add MAKEFLAGS= to avoid using flags from ABS in CARGO
RUST_CARGO_CMD=MAKEFLAGS= $(if $(shell which sccache),RUSTC_WRAPPER=sccache) PATH=$(RUST_BIN_DIR):$$PATH CARGO_TARGET_DIR=$(RUST_TARGET_DIR) $(RUST_BIN_DIR)cargo

$(RUST_CARGO_EXECUTED): $(RUSTSRCFILES) $(CARGO_TOML) $(PRJOBJDIR)/$(MODNAME)/.depready $(foreach mod,$(USEMOD),$(wildcard $(TRDIR)/lib/lib$(USEMOD).rlib))
	@mkdir -p $(@D)
	$(RUST_CARGO_CMD) rustc $(CARGO_OPTS) -- $(RUSTFLAGS)
	@touch $@

run:: $(RUST_TARGET_FILE_BIN)
	@LD_LIBRARY_PATH=$(TRDIR)/lib:$(RUST_LIB_DIR) $(RUST_TARGET_FILE_BIN)

test:: $(RUST_CARGO_EXECUTED)
	@$(RUST_CARGO_CMD) test $(CARGO_OPTS) $(T)

$(RUST_TARGET_FILE_BIN): $(RUST_CARGO_EXECUTED)
	@mkdir -p $(@D)
	@$(ABS_PRINT_info) "Copy generated binary to $@"
	@cp $(RUST_TARGET_DIR)/$(MODE)/$(APPNAME)_$(MODNAME)$(TARGET_EXT) $@

$(RUST_TARGET_FILE_RLIB): $(RUST_CARGO_EXECUTED)
	@mkdir -p $(@D)
	@$(ABS_PRINT_info) "Copy generated rlib to $@"
	@cp $(RUST_TARGET_DIR)/$(MODE)/lib$(APPNAME)_$(MODNAME).rlib $@

$(RUST_TARGET_FILE_SO): $(RUST_CARGO_EXECUTED)
	@mkdir -p $(@D)
	@$(ABS_PRINT_info) "Copy generated dynamic lib to $@"
	@cp $(RUST_TARGET_DIR)/$(MODE)/lib$(APPNAME)_$(MODNAME)$(SOEXT) $@

$(RUST_TARGET_FILE_RUST_SO): $(RUST_CARGO_EXECUTED)
	@mkdir -p $(@D)
	@$(ABS_PRINT_info) "Copy generated rust dynamic lib to $@"
	@cp $(RUST_TARGET_DIR)/$(MODE)/lib$(APPNAME)_$(MODNAME)$(SOEXT) $@

#remove a-zA-Z from VERSION because version must be MAJOR.MINOR.PATCH in rust.
$(CARGO_TOML): $(CARGO_TOML_TEMPLATE) module.cfg $(PRJROOT)/app.cfg
	@$(ABS_PRINT_info) "Generation of $(MODNAME)/$(@F)."
	@echo "# File generated by module-rust.mk. Must not be modified manually" > $@.tmp
	@echo "# This file is regenerated at each compilation." >> $@.tmp
	@VERSION=`echo $(VERSION) | sed 's/[a-zA-Z]//g'` && \
		grep -E -v "^#.*" $< | \
		sed -e "s/@NAME@/$(APPNAME)_$(MODNAME)/g" \
			-e "s/@VERSION@/$$VERSION/g" \
		    -e "s~@DEPENDENCIES@~$(RUST_DEPENDS_TEXT)~g" \
			-e "s/@RUST_EDITION@/$(RUST_EDITION)/g" \
			-e "s/@CREATE_TYPE@/$(subst $(_space_),$(_comma_),$(patsubst %,'%',$(CRATETYPE)))/g" \
			>> $@.tmp
	@test ! -f $@ || chmod +w $@
	@chmod -w $@.tmp
	@mv $@.tmp $@

.ONESHELL:
$(CARGO_TOML_TEMPLATE):
	@cat << EOF > $@
		# File generated by module-rust.mk
		# Can be modified to add dependencies or other elements.
		# Variable with @ are replaced during compilation.
		[package]
		name = "@NAME@"
		version = "@VERSION@"
		edition = '@RUST_EDITION@'
		EOF
	@test '$(ONE_CRATETYPE)' == 'lib' && cat << EOF >> $@
		[lib]
		crate-type = [@CREATE_TYPE@]
		EOF
	@echo "[dependencies]" >> $@
	@echo "@DEPENDENCIES@" >> $@

