<?xml version="1.0" encoding="UTF-8"?><cr id="1c883c3545fc40b96f5aedc7de54501de7815f3e9506fed4c2ca90f69f873f12" state="resolved">
    <title>Unit test report no more readable by jenkins</title>
    <reporter>sdevaux</reporter>
    <creation>2021-11-28 12:03:29+01:00</creation>
    <description>
        <p>XML test report generated by the test traget are not more readable by Jenkins.</p>
        <p>XSD file to use for checking the format is available on git hub at:</p>
        <p>https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd</p>
    </description>
    <links>
        <link name="parent"> bfca44f877c9cb6e2fbd92dbec6ba421c47c889dc70d28b370b8aa9013a7f45e</link>
    </links>
    <cf v="sdevaux 2021-11-28T12:04:42+01:00"> </cf>
</cr>
