QUARTUS_CPFFLAGS:=-o bitstream_compression=on
DE10NANO_PROFILE?=nohps
QUARTUS_QSF_TEMPLATE:=$(FPGA_EXT_PATH)/de10nano/de10nano_$(DE10NANO_PROFILE).qsf
QUARTUS_SDC:=$(FPGA_EXT_PATH)/de10nano/de10nano_$(DE10NANO_PROFILE).sdc
TOP_LEVEL_TEMPLATE:=$(FPGA_EXT_PATH)/de10nano/de10nano_$(DE10NANO_PROFILE).v
