name: PublishTag

on:
  push:
    tags:
      - 'abs-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build abs package
        run: |
          make dist
          export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "${{ secrets.MONETA_PUB_KEY }}" > ~/.ssh/known_hosts
          scp -P 17022 dist/abs-*.tar.gz github@moneta.eduvax.net:~
